coverage:
  ignore:
    - borax/ui/*.py
    - borax/apps/festival_creator.py
    - borax/calendars/datepicker.py
    - borax/calendars/ui.py
    - borax/capp/*.py
  status:
    project:
      default:
        target: 85%
        threshold: 5%
    patch:
      default:
        target: 85%
        threshold: 5%
    changes: no
